name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Build using maven
      working-directory: plugin
      run: mvn -B package --file pom.xml

    - name: configure tag name
      id: tag
      run: echo ::set-output name=tag::$(date +'%Y%m%d')-$(git rev-parse --short ${{ github.sha }})

    - name: Create GitHub release
      uses: ncipollo/release-action@v1.15.0
      with:
          tag: ${{ steps.tag.outputs.tag }}
          allowUpdates: true
          prerelease: true

    - name: Upload jar files to GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "plugin/target/*.jar"
          file_glob: true
          tag: ${{ steps.tag.outputs.tag }}
